# Generated by Django 4.2.3 on 2024-01-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent', '0001_initial'),
        ('user_idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetalentidea',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_idea.idea'),
        ),
    ]
