# Generated by Django 4.2.3 on 2023-12-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('talent', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetalentidea',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='invitetalentidea',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talent', to='users.userprofile'),
        ),
    ]
