# Generated by Django 4.2.3 on 2023-12-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_idea', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='slug',
            field=models.SlugField(blank=True, max_length=78, null=True, unique=True),
        ),
    ]
