# Generated by Django 4.2.3 on 2023-12-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_view',
            field=models.IntegerField(default=0),
        ),
    ]
